
  {{ BCC_ORDERER_ADDR }}:
    container_name: {{ BCC_ORDERER_ADDR }}
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT={{ BCC_ORDERER_PORT }}
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID={{ BCC_ORDERER_NAME }}MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - {{ BCC_ORDERER_PORT }}:{{ BCC_ORDERER_PORT }}
    volumes:
        - ./../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./../organizations/ordererOrganizations/{{ BCC_NETWORK_DOMAIN }}/orderers/{{ BCC_ORDERER_ADDR }}/msp:/var/hyperledger/orderer/msp
        - ./../organizations/ordererOrganizations/{{ BCC_NETWORK_DOMAIN }}/orderers/{{ BCC_ORDERER_ADDR }}/tls/:/var/hyperledger/orderer/tls
        - {{ BCC_ORDERER_ADDR }}:/var/hyperledger/production/orderer
    networks:
      - {{ BCC_NETWORK_DOMAIN }}

