
  {{ BCC_PEER_ADDR }}:
    container_name: {{ BCC_PEER_ADDR }}
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      #- FABRIC_LOGGING_SPEC=INFO
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID={{ BCC_PEER_ADDR }}
      - CORE_PEER_ADDRESS={{ BCC_PEER_ADDR }}:{{ BCC_PEER_PORT }}
      - CORE_PEER_LISTENADDRESS={{ BCC_PEER_ADDR }}:{{ BCC_PEER_PORT }}
      - CORE_PEER_CHAINCODEADDRESS={{ BCC_PEER_ADDR }}:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP={{ BCC_PEER_ADDR }}:{{ BCC_PEER_PORT }}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT={{ BCC_PEER_ADDR }}:{{ BCC_PEER_PORT }}
      - CORE_PEER_LOCALMSPID={{ BCC_ORG_NAME }}MSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - {{ BCC_PEER_PORT }}:{{ BCC_PEER_PORT }}
    volumes:
        - /var/run/:/host/var/run/
        - ./../organizations/peerOrganizations/{{ BCC_ORG_ADDR }}/peers/{{ BCC_PEER_ADDR }}/msp:/etc/hyperledger/fabric/msp
        - ./../organizations/peerOrganizations/{{ BCC_ORG_ADDR }}/peers/{{ BCC_PEER_ADDR }}/tls:/etc/hyperledger/fabric/tls
        - ./../channel-artifacts:/etc/hyperledger/configtx
        - {{ BCC_PEER_ADDR }}:/var/hyperledger/production
    networks:
      - {{ BCC_NETWORK_DOMAIN }}

